spring:
  datasource:
    username: root
    password: password
    url:  jdbc:mysql://127.0.0.1:3306/contract_start?characterEncoding=UTF-8
  jpa:
    show-sql: true
    database: mysql
server:
  port: 8090
